### ISSUE TITLE
slows down the animation of the flow on the pipes

### ISSUE THREAD

**Issue by dimontau** [PiBrewing/craftbeerpi4-ui#40]
Hello. After the update, the animation of the flow on the pipes began to slow down. Before that everything was fine.
Is it also possible to add a buzzer sound to the web browser?

**Comment by avollkopf** [comment]
Unfortunately, you didn't share information from which version you have been upgrading. Last Year in July, there was a PR implemented that introduced a parameter slow_pipe_animation in the settings (https://github.com/PiBrewing/craftbeerpi4-ui/commit/96ddce71e974be49d6dec748cb15d907e53188e1). Here you can change the setting from yes to no which should most likely solve your issue.

Although, off topic in contrast to the title of this issue. Try the latest development versions of Server and UI. A global setting PLAY_BUZZER and a sound on Notifications got introduced if set to yes. Please don't complain about the sound itself. I am extremely limited on potential free sound sources.

**Comment by dimontau** [comment]
Can't find the PLAY_BUZZER setting. Where to change?

**Comment by avollkopf** [comment]
Please read the development part of the documentation. [Installation of development versions](https://openbrewing.gitbook.io/craftbeerpi4_support/readme/development) is described there in detail.
