### ISSUE TITLE
cbpi4_compressorActor vs Craftbeerpi-ui

### ISSUE THREAD

**Issue by stpoli2468** [PiBrewing/craftbeerpi4-ui#54]
Hi, i saw on facebook that a few month ago you made the changes from pascal1404\craftbeerpi repo, and it works.
but he made also changes to craftbeerpi-ui. with those change we could make an actor button and the text on it displayed the timer countdown.
can you check if it is possible to implement it, or make another object type "timer" for the ui that connects on a actor/sensor delay?
Thanks!

**Comment by avollkopf** [comment]
Please check out development branch. changes made [here](https://github.com/PiBrewing/craftbeerpi4-ui/commit/41e2feddd1d80ae40e536aa24bd608e4ade824f2)

![image](https://github.com/user-attachments/assets/43334a9f-d6bd-4cde-a38d-34249e196251)
